---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.0

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[artifact-deployer::default]
    attributes: {
      artifacts: {
        junit1: {
          enabled: true,
          groupId : "junit",
          artifactId : "junit",
          version : "4.11",
          destination: "/home/vagrant/default_suite",
          owner: "root",
          # Force failure by setting timeout to 1 sec
          # timeout: 1
        },
        junit2: {
          groupId : "junit",
          artifactId : "junit",
          version : "4.11",
          destination: "/home/vagrant/disabled_suite",
          owner: "root"
        },
        junit3: {
          enabled: true,
          unzip: true,
          groupId : "junit",
          artifactId : "junit",
          version : "4.11",
          destination: "/home/vagrant/subfolder_suite",
          subfolder: "META-INF/\\*",
          owner: "root"
        },
        s3bucket: {
          enabled: true,
          s3_bucket: "artifact-deployer-test",
          destination: "/home/vagrant",
          owner: "root"
        },
        s3file: {
          enabled: true,
          unzip: true,
          s3_bucket: "artifact-deployer-test",
          s3_filename: "keep-calm-and-daje-forte.png.zip",
          destination: "/home/vagrant",
          owner: "root"
        }
      }
    }
